using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerController : MonoBehaviour
{
    //IN CLASS COLLEGE NOW MW

    //GLOBAL VARIABLES
    public Rigidbody2D playerBody;

    public float playerSpeed = 0.05f;
    public float jumpForce = 300;
    public bool isJumping = false; 

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        MovePlayer();
        Jump(); 
    }

    private void MovePlayer()
    {
        Vector3 newPos = transform.position;

        if (Input.GetKey(KeyCode.A))
        {
            //Debug.Log("A pressed"); //print to console
            newPos.x -= playerSpeed; //go left
        }
        else if (Input.GetKey(KeyCode.D))
        {
            //Debug.Log("D pressed"); //print to console
            newPos.x += playerSpeed; //go right
        }
        transform.position = newPos; 
    }

    private void Jump()
    {
        if (!isJumping && Input.GetKeyDown(KeyCode.Space))
        {
            playerBody.AddForce(new Vector3(playerBody.velocity.x, jumpForce, 0));
            isJumping = true; 
        }
    }

    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.gameObject.tag == "Surface")
        {
            isJumping = false; 
        }
    }
}
